# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  api.hooke.design:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "(}?HV)FLawKPJn2zG[OTSQGXo*)/81Tq>mMXm@s&Q[*A.Rz!?=&J,j}om5jffCSA"
      secure_auth_key: "Q9_XT^>h.SrXsUr[.A`+dUA7kR{%a.k&p;$(ecn#00;?^Sy^mtPKR4O}n713-Vni"
      logged_in_key: "{3&Ev}XbCX*URddS1%:UdnTcCR/V`$Jejz,k>#ch{fpeM3Jwl{KL1Q(ymEvqx6kD"
      nonce_key: "ydxe|L]3Le[4eG-+IYO,$)x`n[*qgsjRSl0+>{i8bL;G;0!w<1#VJ/7?BnC-D</K"
      auth_salt: "Ud:9+)LWjVUOddbx>|3YkIz7g+Vrp2-Y79_AaIizdUJu:8AWSxTQ*[z0QR6Ki.<h"
      secure_auth_salt: "TW94XYjc!9gW69ZkB,4A]fp!s$H5s!PbO27zPG6Ys[1rpYVk3j{;ME*0T]=[QfdL"
      logged_in_salt: "z|6>wBAnO;xEZhKC`}9TDSn!0K}w.8P:snuqqTbi7zWdZn;Ef?6cgwp|mQ=<I_X5"
      nonce_salt: ")=wi+MDZ4`d!T>R]?j&u{s(o!ZBR!4=2nNHbzc%8eP!Bxf65GSY(#>zKAz=39kaw"
