# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  api.hooke.design:
    site_hosts:
      - canonical: api.hooke.design
        # redirects:
        #   - otherdomain.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:gromila-developer/api.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: true
      subdomains: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
